(rule
 (target CamlSurf_x11.ml)
 (action (write-file %{target} "include Surfaces")))

(rule
 (target CamlSurf_wayland.ml)
 (action (write-file %{target} "include Surfaces")))

(rule
 (target fragment_light_implicit.ml)
 (deps shaders/fragment_light_implicit.glsl)
 (action
  (with-stdout-to %{target}
   (run glsl_to_ml %{deps}))))

(rule
 (target preambule.ml)
 (deps shaders/preambule.glsl)
 (action
  (with-stdout-to %{target}
   (run glsl_to_ml %{deps}))))

(rule
 (target fragment_text.ml)
 (deps shaders/fragment_text.glsl)
 (action
  (with-stdout-to %{target}
   (run glsl_to_ml %{deps}))))

(rule
 (target solve.ml)
 (deps shaders/solve.glsl)
 (action
  (with-stdout-to %{target}
   (run glsl_to_ml %{deps}))))

(rule
 (target vertex_implicit.ml)
 (deps shaders/vertex_implicit.glsl)
 (action
  (with-stdout-to %{target}
   (run glsl_to_ml %{deps}))))

(rule
 (target vertex_text.ml)
 (deps shaders/vertex_text.glsl)
 (action
  (with-stdout-to %{target}
   (run glsl_to_ml %{deps}))))

(library
 (name formal)
 (preprocess (per_module ((pps pacomb.ppx) Algebra Expression Gen)))
 (modules algebra expression gen)
 (libraries pacomb))

(executable
 (name CamlSurf_x11)
 (public_name CamlSurf_x11)
 (modules CamlSurf_x11 surfaces preambule  fragment_light_implicit  fragment_text  solve vertex_implicit  vertex_text  )
 (flags (:standard -w -6))
 (package CamlSurf-x11)
 (libraries gles3 gles3-x11 pacomb formal))

(executable
 (name CamlSurf_wayland)
 (public_name CamlSurf_wayland)
 (modules CamlSurf_wayland surfaces preambule  fragment_light_implicit  fragment_text  solve  vertex_implicit  vertex_text  )
 (flags (:standard -w -6))
 (package CamlSurf-wayland)
 (libraries gles3 gles3-wayland pacomb formal))
