name: build

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    # Prime the caches every Monday
    - cron: '0 1 * * MON'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-22.04
        ocaml-compiler:
          - "5.2"
          - "5.3"
          - "5.4"
          - "5.5"

    runs-on: ${{ matrix.os }}

    steps:
      - run: sudo apt-get update
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: |
          opam pin add pacomb git+https://github.com/craff/pacomb.git -y
          opam pin add gles3-stubs git+https://github.com/craff/gles3.git -y
          opam pin add gles3 git+https://github.com/craff/gles3.git -y
          opam pin add gles3-x11 git+https://github.com/craff/gles3.git -y
          opam pin add gles3-wayland git+https://github.com/craff/gles3.git -y

      - run: opam install ./CamlSurf-x11.opam ./CamlSurf-wayland.opam --deps-only --with-test

      - run: opam exec -- dune build @install

      - run: opam install CamlSurf-x11 CamlSurf-wayland

  build-container:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:
          - archlinux
          - fedora

    container:
      image: ocaml/opam:${{ matrix.distro }}
      options: --user root

    steps:
      - name: Install tools
        run: |
          if [ "${{ matrix.distro }}" = "archlinux" ]; then
            pacman -Sy --noconfirm nodejs npm git
          else
            dnf install -y nodejs npm git
          fi

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Fix permissions
        run: |
          chown -R opam:opam "$GITHUB_WORKSPACE"

      - name: Opam init
        run: |
          su opam -c '
            opam init --disable-sandboxing -y
            opam switch create ocaml5.5 5.5.0
            '

      - name: Deps
        run: |
          su opam -c '
            opam switch set ocaml5.5
            cd "$GITHUB_WORKSPACE"
            opam pin add pacomb git+https://github.com/craff/pacomb.git -y
            opam pin add gles3-stubs git+https://github.com/craff/gles3.git -y
            opam pin add gles3 git+https://github.com/craff/gles3.git -y
            opam pin add gles3-x11 git+https://github.com/craff/gles3.git -y
            opam pin add gles3-wayland git+https://github.com/craff/gles3.git -y
            opam install ./CamlSurf-x11.opam ./CamlSurf-wayland.opam --deps-only --with-test
            '

      - name: Build
        run: |
          su opam -c '
            opam switch set ocaml5.5
            cd "$GITHUB_WORKSPACE"
            opam exec -- dune build @install
            '

      - name: Install
        run: |
          su opam -c '
            opam switch set ocaml5.5
            cd "$GITHUB_WORKSPACE"
            opam install ./CamlSurf-x11.opam ./CamlSurf-wayland.opam
            '
